# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchday',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='matchday',
            name='start_date',
            field=models.DateField(),
        ),
    ]
